const express = require("express");
const cors = require("cors");
const morgan = require("morgan");
const authRoutes = require("./routes/authRoutes");
const fileRoutes = require("./routes/fileRoutes");
const assetRoutes = require("./routes/assetRoutes");
const categoryRoutes = require("./routes/categoryRoutes");
const app = express();
app.use(cors());
app.use(express.json());
app.use(morgan("dev"));
app.use("/AssetManagement/auth", authRoutes);
app.use("/AssetManagement/file", fileRoutes);
app.use("/AssetManagement/asset", assetRoutes);
app.use("/AssetManagement/category", categoryRoutes);
module.exports = app;
