const express = require("express");
const cors = require("cors");
const morgan = require("morgan");
const authRoutes = require("./routes/authRoutes");
const app = express();
app.use(cors());
app.use(express.json());
app.use(morgan("dev"));
app.use("/AssetManagement/auth", authRoutes);
module.exports = app;
